### ISSUE TITLE
cannot start the application - 'linien-influxdb' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by yasio90** [linien-org/linien-influxdb#11]
After installing linien-influxdb with pip I tried to run it as recommended in the manual and got the following error
`'linien-influxdb' is not recognized as an internal or external command`
I'm working on Windows 10 and use Anaconda. Any help would be very welcome.

**Comment by bleykauf** [comment]
Sorry for the late reply. Indeed, I can also not get this to work on Windows.

I am actually not very happy with how the whole program is set up:

* Don't see the need for separate processes for pushing and pulling
* Not compatible with influxdb2
* Separate shell script instead of using click directly

I already have a private project for influxdb logging and will try to port this for the specific case of linien. This will be a complete rewrite of `linien-influxdb` and will probably only work for influxdb2 (there were a lot of changes between 1.8 and 2). Please let me know if you rely on the (now outdated) influxdb 1.8, @yasio90. If so, I might add support for it as well.

I also have a work-in-progress branch (https://github.com/linien-org/linien/tree/feature/influxd) to put the logging on the RedPitaya itself. But I will not have the time to finish this any time soon so I think it is worth the effort for this intermediate solution.

Will update here if I push changes. Testing from your side would then be much appreciated.

**Comment by bleykauf** [comment]
Progress can be trackedin #12

**Comment by bleykauf** [comment]
@yasio90 Version 2.0.0 is now up on pypi

Will add some documentation in a minute

**Comment by yasio90** [comment]
Cool! Great thanks. It works very well. We observed one issue - I reported it here: #18

**Comment by bleykauf** [comment]
Sorry, in fact the logging to influxdb did did not work, I only tested for with `--print-only`, bad idea.

Will push a fix soon...
